baseURL = "https://aniotaofthought.com/"
languageCode = "en-us"
title = "An iota of thought"
theme = "kiss"
copyright = "&copy; All copyrights reserved by <a href=\"https://abhishekdeydas.com\">Abhishek Dey Das</a>. All opinions are personal and does not reflect that of my employer or organizations I am associated with."
Paginate = 5
disqusShortname = "an-iota-of-thought"

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "An iota of thought" # Title for home page
related = true # Includes related articles at the bottom of the article

[taxonomies]
tag ="tags"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "https://abhishekdeydas.com/"
[[menu.main]]
    name = "Photos"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "https://abhishekdeydas.com/photos/"
[[menu.main]]
    name = "Source code"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "https://github.com/adeydas/aniotaofthought.com"